/**
 * Element Plus 图标名称 -> Lucide 图标映射
 * 将 Vue 版本使用的 Element Plus 图标映射到 React 的 lucide-react 图标
 */

import * as Icons from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// Element Plus 图标名称 -> Lucide 图标映射（完整版）
export const elementIconMap: Record<string, LucideIcon> = {
  // 方向指示
  Back: Icons.ArrowLeft,
  Right: Icons.ArrowRight,
  Bottom: Icons.ArrowDown,
  Top: Icons.ArrowUp,
  Left: Icons.ArrowLeft,
  CaretLeft: Icons.ChevronLeft,
  CaretRight: Icons.ChevronRight,
  CaretBottom: Icons.ChevronDown,
  CaretTop: Icons.ChevronUp,
  ArrowDown: Icons.ArrowDown,
  ArrowDownBold: Icons.ArrowDown,
  ArrowLeft: Icons.ArrowLeft,
  ArrowLeftBold: Icons.ArrowLeft,
  ArrowRight: Icons.ArrowRight,
  ArrowRightBold: Icons.ArrowRight,
  ArrowUp: Icons.ArrowUp,
  ArrowUpBold: Icons.ArrowUp,
  DArrowLeft: Icons.ChevronsLeft,
  DArrowRight: Icons.ChevronsRight,
  DCaret: Icons.ChevronsUpDown,
  TopLeft: Icons.ArrowUpLeft,
  TopRight: Icons.ArrowUpRight,
  BottomLeft: Icons.ArrowDownLeft,
  BottomRight: Icons.ArrowDownRight,
  
  // 操作相关
  Plus: Icons.Plus,
  Minus: Icons.Minus,
  Close: Icons.X,
  CloseBold: Icons.X,
  Check: Icons.Check,
  Checked: Icons.CheckCircle,
  Edit: Icons.Pencil,
  EditPen: Icons.PenLine,
  Delete: Icons.Trash2,
  DeleteFilled: Icons.Trash2,
  Search: Icons.Search,
  Refresh: Icons.RefreshCw,
  RefreshLeft: Icons.RotateCcw,
  RefreshRight: Icons.RotateCw,
  Upload: Icons.Upload,
  UploadFilled: Icons.Upload,
  Download: Icons.Download,
  Remove: Icons.Minus,
  RemoveFilled: Icons.MinusCircle,
  CirclePlus: Icons.PlusCircle,
  CirclePlusFilled: Icons.PlusCircle,
  CircleCheck: Icons.CheckCircle,
  CircleCheckFilled: Icons.CheckCircle2,
  CircleClose: Icons.XCircle,
  CircleCloseFilled: Icons.XCircle,
  Select: Icons.Check,
  SemiSelect: Icons.Minus,
  Sort: Icons.ArrowUpDown,
  SortDown: Icons.ArrowDown,
  SortUp: Icons.ArrowUp,
  Expand: Icons.Expand,
  Fold: Icons.Minimize2,
  FullScreen: Icons.Maximize,
  ScaleToOriginal: Icons.Minimize,
  ZoomIn: Icons.ZoomIn,
  ZoomOut: Icons.ZoomOut,
  Crop: Icons.Crop,
  Filter: Icons.Filter,
  Rank: Icons.Trophy,
  
  // 数据展示
  DataLine: Icons.LineChart,
  DataBoard: Icons.LayoutDashboard,
  DataAnalysis: Icons.BarChart2,
  PieChart: Icons.PieChart,
  TrendCharts: Icons.TrendingUp,
  Histogram: Icons.BarChart3,
  List: Icons.List,
  Grid: Icons.Grid3x3,
  
  // 文件相关
  Document: Icons.FileText,
  DocumentAdd: Icons.FilePlus,
  DocumentChecked: Icons.FileCheck,
  DocumentCopy: Icons.Files,
  DocumentDelete: Icons.FileX,
  DocumentRemove: Icons.FileMinus,
  Folder: Icons.Folder,
  FolderOpened: Icons.FolderOpen,
  FolderAdd: Icons.FolderPlus,
  FolderChecked: Icons.FolderCheck,
  FolderDelete: Icons.FolderX,
  FolderRemove: Icons.FolderMinus,
  Files: Icons.Files,
  CopyDocument: Icons.Copy,
  Management: Icons.ClipboardList,
  Postcard: Icons.Mail,
  Paperclip: Icons.Paperclip,
  
  // 设备硬件
  Monitor: Icons.Monitor,
  Cpu: Icons.Cpu,
  Printer: Icons.Printer,
  Mouse: Icons.Mouse,
  Camera: Icons.Camera,
  CameraFilled: Icons.Camera,
  Cellphone: Icons.Smartphone,
  Iphone: Icons.Smartphone,
  Headset: Icons.Headphones,
  Mic: Icons.Mic,
  Microphone: Icons.Mic,
  VideoCamera: Icons.Video,
  VideoCameraFilled: Icons.Video,
  VideoPlay: Icons.Play,
  VideoPause: Icons.Pause,
  
  // 用户相关
  User: Icons.User,
  UserFilled: Icons.User,
  Avatar: Icons.UserCircle,
  Male: Icons.User,
  Female: Icons.User,
  Lock: Icons.Lock,
  Unlock: Icons.Unlock,
  Key: Icons.Key,
};
